/**
 * frida-youtube-transcript — obtiene la transcripción de un video de YouTube.
 *
 * A diferencia de `pi-youtube-transcript` (que hace un fetch naive de la watch
 * page + timedtext y topa con el muro anti-bot / rate-limit de YouTube), este
 * tool envuelve `yt-dlp` usando la **sesión logueada del navegador** del usuario
 * (`--cookies-from-browser`) + el solver de challenges nsig/PO-token
 * (`--remote-components ejs:github`, requiere `deno`). Así las peticiones van
 * como usuario autenticado → sin bot-check ni límites diarios agresivos → apto
 * para lotes de varios videos.
 *
 * Ver ADR-0049 / issue #37.
 *
 * Prerrequisitos (se verifican en runtime con mensajes claros):
 * - `yt-dlp` en el PATH (o en `~/.local/bin`).
 * - `deno` en el PATH (o en `/opt/homebrew/bin`) — runtime JS para resolver los
 *   challenges de YouTube.
 * - Sesión de YouTube logueada en el navegador configurado (por defecto `brave`).
 *
 * Main only: usa el navegador y herramientas externas del host; las sesiones
 * hijas de workflow no las necesitan.
 */

import type {
	AgentToolResult,
	ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { execFile } from "node:child_process";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export interface FridaYoutubeTranscriptOptions {
	/** Navegador del que extraer las cookies de sesión de YouTube. Default: "brave". */
	browser?: string;
}

interface TranscriptDetails extends Record<string, unknown> {
	videoId: string;
	language: string;
	chars: number;
	segments: number;
	/** Captions generadas automáticamente (auto) vs subidas manualmente. */
	autoGenerated: boolean;
}

/** Segmento de texto dentro de un evento de caption json3. */
interface CaptionSeg {
	utf8?: string;
}

/** Evento de caption json3 (startTime ms + segmentos de texto). */
interface CaptionEvent {
	tStartMs?: number;
	segs?: CaptionSeg[];
}

/** Estructura json3 que produce yt-dlp. */
interface Json3Transcript {
	events?: CaptionEvent[];
}

/** Aumenta el PATH para encontrar yt-dlp (~/.local/bin) y deno (/opt/homebrew/bin). */
function augmentedPath(): string {
	const extra = [
		join(homedir(), ".local", "bin"),
		"/opt/homebrew/bin",
		"/usr/local/bin",
	];
	const current = process.env.PATH ?? "";
	return [...extra, current].filter(Boolean).join(":");
}

/** Detecta yt-dlp y deno en el PATH ampliado; lanza con mensaje claro si faltan. */
async function ensureDeps(): Promise<void> {
	const env = { ...process.env, PATH: augmentedPath() };
	const checks: Array<{ bin: string; hint: string; install: string }> = [
		{
			bin: "yt-dlp",
			hint: "yt-dlp no está en el PATH",
			install: "pip3 install --user yt-dlp  (o: brew install yt-dlp)",
		},
		{
			bin: "deno",
			hint: "deno no está en el PATH (runtime JS para resolver challenges de YouTube)",
			install: "brew install deno",
		},
	];
	for (const { bin, hint, install } of checks) {
		try {
			await execFileAsync("which", [bin], { env });
		} catch {
			throw new Error(
				`${hint}. Instálalo:\n  ${install}\ny reinicia el host de Frida.`,
			);
		}
	}
}

/** Extrae el ID de 11 chars de una URL o de un ID suelto. */
export function extractVideoId(input: string): string {
	const trimmed = input.trim();
	if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;
	const patterns = [
		/[?&]v=([a-zA-Z0-9_-]{11})/i,
		/youtu\.be\/([a-zA-Z0-9_-]{11})/i,
		/(?:www\.|m\.)?youtube\.com\/(?:embed|v|e|shorts|live)\/([a-zA-Z0-9_-]{11})/i,
	];
	for (const re of patterns) {
		const m = trimmed.match(re);
		if (m) return m[1];
	}
	// Pasar tal cual y dejar que yt-dlp falle si es inválido.
	return trimmed;
}

interface ParsedTranscript {
	text: string;
	segments: number;
}

/** Parsea el json3 de yt-dlp a texto plano (eventos concatenados). */
function parseJson3(raw: string): ParsedTranscript {
	let data: Json3Transcript;
	try {
		data = JSON.parse(raw) as Json3Transcript;
	} catch {
		throw new Error("La transcripción descargada no es JSON válido (json3).");
	}
	const events = data.events ?? [];
	let parts = "";
	let segCount = 0;
	for (const ev of events) {
		if (!ev.segs) continue;
		segCount++;
		for (const seg of ev.segs) parts += seg.utf8 ?? "";
	}
	const text = parts.replace(/\n{3,}/g, "\n\n").trim();
	if (!text) {
		throw new Error("La transcripción descargada está vacía.");
	}
	return { text, segments: segCount };
}

/**
 * Ejecuta yt-dlp con cookies del navegador + solver de challenges en un tmp dir,
 * lee el .json3 generado y limpia. Devuelve el texto parseado + idioma inferido.
 */
async function fetchTranscript(
	videoId: string,
	lang: string,
	browser: string,
	signal: AbortSignal | undefined,
): Promise<{ parsed: ParsedTranscript; language: string }> {
	const env = { ...process.env, PATH: augmentedPath() };
	const tmpDir = await mkdtemp(join(tmpdir(), "frida-yt-"));
	try {
		const args = [
			"--cookies-from-browser",
			browser,
			"--skip-download",
			"--no-playlist",
			"--write-auto-subs",
			"--sub-langs",
			lang,
			"--sub-format",
			"json3",
			"--remote-components",
			"ejs:github",
			"-o",
			join(tmpDir, "%(id)s"),
			`https://www.youtube.com/watch?v=${videoId}`,
		];
		const { stderr } = await execFileAsync("yt-dlp", args, {
			env,
			signal,
			maxBuffer: 16 * 1024 * 1024,
			timeout: 180_000,
		});

		const entries = await readdir(tmpDir);
		const json3 = entries.find((f) => f.endsWith(".json3"));
		if (!json3) {
			const tail = (stderr || "").slice(-800);
			throw new Error(
				`yt-dlp no generó la transcripción.${tail ? `\nSalida de yt-dlp:\n${tail}` : ""}`,
			);
		}
		const raw = await readFile(join(tmpDir, json3), "utf8");
		const parsed = parseJson3(raw);
		// Idioma inferido del nombre: <videoId>.<lang>.json3
		const m = json3.match(/\.([a-zA-Z-]{2,})\.json3$/);
		return { parsed, language: m ? m[1] : lang };
	} finally {
		await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
	}
}

// biome-ignore lint/complexity/useMaxParams: firma execute del SDK
async function runTranscript(
	_toolCallId: string,
	params: unknown,
	signal: AbortSignal | undefined,
	browser: string,
): Promise<AgentToolResult<TranscriptDetails>> {
	const { videoIdOrUrl, lang = "en" } = params as {
		videoIdOrUrl: string;
		lang?: string;
	};
	const videoId = extractVideoId(videoIdOrUrl);

	await ensureDeps();
	const { parsed, language } = await fetchTranscript(videoId, lang, browser, signal);

	return {
		content: [{ type: "text", text: parsed.text }],
		details: {
			videoId,
			language,
			chars: parsed.text.length,
			segments: parsed.segments,
			autoGenerated: true,
		},
	};
}

/**
 * Factory. Sigue el patrón `createFridaXxx()` de las tools internas: devuelve
 * `(pi) => { registra el tool }`.
 */
export function createFridaYoutubeTranscript(
	opts: FridaYoutubeTranscriptOptions = {},
) {
	const browser = opts.browser ?? "brave";
	return (pi: ExtensionAPI): void => {
		pi.registerTool({
			name: "youtube_transcript",
			label: "YouTube Transcript",
			description:
				"Fetch the transcript of a YouTube video by URL or video ID. Uses yt-dlp with the user's logged-in browser session (Brave) so it bypasses YouTube bot detection and daily limits — suitable for batches of many videos.",
			promptSnippet:
				"Fetch a YouTube video transcript by URL or video ID (uses the logged-in browser session).",
			promptGuidelines: [
				"Use youtube_transcript when the user asks about the content of a YouTube video.",
				"It works for many videos in a row (uses the authenticated browser session, no daily limits).",
			],
			parameters: Type.Object({
				videoIdOrUrl: Type.String({
					description: "YouTube video ID or full URL (watch, youtu.be, shorts, embed).",
				}),
				lang: Type.Optional(
					Type.String({
						description:
							"Preferred language code (e.g. 'en', 'es'). Falls back to the first available transcript if omitted. Default: 'en'.",
					}),
				),
			}),
			// biome-ignore lint/complexity/useMaxParams: firma execute del SDK
			execute: (id, params, signal) =>
				runTranscript(id, params, signal, browser),
		});
	};
}
